### ISSUE TITLE
Keplr goes blank when I switch to Sifchain

### ISSUE THREAD

**Issue by emperorjm** [chainapsis/keplr-extension#84]
Whenever I switch from Cosmos to the Sifchain network the Keplr screen goes blank and I am not able to select any options. Any subsequent tries to open the plugin leads to a blank popup.

**Comment by emperorjm** [comment]
When I click incpect I see the following list of errors:

Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
    at de (chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/popup.bundle.js:77:362656)
    at chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/popup.bundle.js:77:509022
popup.bundle.js:53 Uncaught (in promise) Error: Both wasm and asm failed to loadTypeError: Cannot read property 'rc' of undefined
    at popup.bundle.js:53
popup.bundle.js:178 Error: invalid decimal: NaN
    at new a (popup.bundle.js:30)
    at a.get inflation (popup.bundle.js:287)
    at $e (popup.bundle.js:23)
    at e.t.computeValue_ (popup.bundle.js:23)
    at e.t.trackAndCompute (popup.bundle.js:23)
    at e.t.get (popup.bundle.js:23)
    at Ye (popup.bundle.js:23)
    at e.t.runReaction_ (popup.bundle.js:23)
    at kt (popup.bundle.js:23)
    at wt (popup.bundle.js:23)
    at popup.bundle.js:23
    at ac (popup.bundle.js:295)
    at wt (popup.bundle.js:23)
    at _t (popup.bundle.js:23)
    at gt (popup.bundle.js:23)
    at je (popup.bundle.js:23)
es @ popup.bundle.js:178
popup.bundle.js:23 [mobx] uncaught error in 'Reaction[observer]' Error: invalid decimal: NaN
    at new a (popup.bundle.js:30)
    at a.get inflation (popup.bundle.js:287)
    at $e (popup.bundle.js:23)
    at e.t.computeValue_ (popup.bundle.js:23)
    at e.t.trackAndCompute (popup.bundle.js:23)
    at e.t.get (popup.bundle.js:23)
    at Ye (popup.bundle.js:23)
    at e.t.runReaction_ (popup.bundle.js:23)
    at kt (popup.bundle.js:23)
    at wt (popup.bundle.js:23)
    at popup.bundle.js:23
    at ac (popup.bundle.js:295)
    at wt (popup.bundle.js:23)
    at _t (popup.bundle.js:23)
    at gt (popup.bundle.js:23)
    at je (popup.bundle.js:23)

**Comment by emperorjm** [comment]
The latest update 0.8.6 fixed the issue.
